# Generated by Django 2.2.5 on 2020-02-24 01:01

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegoSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=30)),
                ('theme', models.CharField(max_length=20)),
                ('release_date', models.CharField(max_length=20)),
                ('num_parts_need', models.CharField(blank=True, max_length=10)),
                ('price', models.CharField(blank=True, max_length=210)),
            ],
            managers=[
                ('LegoSet', django.db.models.manager.Manager()),
            ],
        ),
    ]
