# Generated by Django 2.2.5 on 2020-02-25 22:24

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mylegos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='legoset',
            managers=[
                ('LegoSets', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='legoset',
            name='price',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
