# Generated by Django 2.2.5 on 2020-02-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylegos', '0002_auto_20200225_1524'),
        ('mylegos', '0002_auto_20200225_1908'),
        ('mylegos', '0002_auto_20200225_1705'),
    ]

    operations = [
    ]
